---
ansible_become: true
apache_vhosts:
  - servername: "{{ hostname }}"
    documentroot: "/var/www/{{hostname}}/current/public"
apache_vhosts_ssl:
  - servername: "{{ hostname }}"
    documentroot: "/var/www/{{hostname}}/current/public"
    certificate_file: "/etc/letsencrypt/live/{{hostname}}/cert.pem"
    certificate_key_file: "/etc/letsencrypt/live/{{hostname}}/privkey.pem"
    certificate_chain_file: "/etc/letsencrypt/live/{{hostname}}/chain.pem"
php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
certbot_auto_renew: true
certbot_create_if_missing: true
certbot_create_method: standalone
certbot_admin_email: latistecharch@umn.edu
certbot_certs:
  - domains:
    - "{{ hostname }}"
certbot_create_standalone_stop_services:
  - httpd
sectigo_eab_kid: "{{ sectigo_kid }}"
sectigo_eab_hmac:  "{{ sectigo_hmac }}"