---
ansible_become: true
apache_vhosts:
  - servername: "{{ hostname }}"
    documentroot: "/var/www/{{hostname}}/current/public"
php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
certbot_auto_renew: true
certbot_create_if_missing: true
certbot_create_method: standalone
certbot_admin_email: latistecharch@umn.edu
certbot_certs:
  - domains:
    - "{{ hostname }}"