---
ansible_become: true
nginx_vhosts:
  - listen: "443 ssl http2"
    server_name: "{{ hostname }}"
    root: "/var/www/html/"
    index: "index.php index.html index.htm"
    error_page: ""
    access_log: ""
    error_log: ""
    state: "present"
    # template: "{{ nginx_vhost_template }}"
    # filename: "example.com.conf"
    extra_parameters: |
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }
      ssl_certificate     /etc/letsencrypt/live/{{hostname}}/cert.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{hostname}}/privkey.pem;
      ssl_protocols       TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;
php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
certbot_auto_renew: true
certbot_create_if_missing: true
certbot_create_method: standalone
certbot_admin_email: latistecharch@umn.edu
certbot_certs:
  - domains:
    - "{{ hostname }}"
certbot_create_standalone_stop_services:
  - nginx
