---
ansible_become: true
deploy_user: "latis_deploy"
umn_user_management_directory_users:
  - name: "mcfa0086"
    revoke: no
    sudo: yes
    authorized_keys: 
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAyEflucZ6zQruAmA5I2CBTE8H6jkMsmg2giLcJ6Hb5zQvBYbqGaawXiLaPfPm8lotlTLf0XR8Q7J39qFYP3diwzYSj9IlG1NSE1nDOvbitMQFn9s08Ei9zi4TJb2rR/tmLYZLlyPsJgoJpEis2nl+IVjJ+uyu99B/94IEsudB7+YIcu11BWlpb5kuVXNkF4XLojoKHsBn9Aeb5DCvOFtzXAgWCAvsbe0b5kOnvu84EBB1wxMmNx6LPe+kd/NrwVEorgQSSX1g/raYVANALCqgVmS3kKF6iVuCBpdfPFwo8djEJPzj7V3QI0Rc2/l6AZ7xCtCU4JCsZGByDiCJ5JRQfQ== mcfa0086@umn.edu'
umn_user_management_deploy_users:
  - name: "latis_deploy"
    uid: 30000
    comment: "LATIS Deploy User"
    primary_group: "latis_deploy"
    shell: /bin/bash
    create_home: yes
    groups: []
    authorized_keys_from_directory_users: yes

db_hostname: ""
db_database: ""
db_username: ""
db_password: ""
secret_key: ""



passenger_server_name: "{{ hostname}}"
passenger_app_root: "/var/www/html/current/public"
passenger_app_env: "remotedev"


nginx_extra_conf_options: |
  load_module modules/ngx_http_passenger_module.so;

nginx_vhosts:
  - listen: "80"
    server_name: "{{ hostname }}"
    return: "301 https://{{hostname}}$request_uri"
    filename: "{{hostname}}.80.conf"
  - listen: "443 ssl http2"
    server_name: "{{ hostname }}"
    root: "/var/www/html/current/public/"
    state: "present"
    # realpath param in nginx config is necessary so that it reloads files when symlink is updated
    extra_parameters: |
      passenger_enabled   "on";
      passenger_ruby     /usr/bin/ruby;
      ssl_certificate     /etc/letsencrypt/live/{{hostname}}/cert.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{hostname}}/privkey.pem;
      ssl_protocols       TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;

ruby_install_from_source: true
ruby_version: 3.3.0
ruby_download_url: https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.0.tar.gz
ruby_install_bundler: true
ruby_build_packages:
  - '@development tools'
  - zlib-devel
  - libffi-devel

certbot_auto_renew: true
certbot_create_if_missing: true
certbot_create_method: standalone
certbot_admin_email: latistecharch@umn.edu
certbot_auto_renew_user: root

certbot_certs:
  - domains:
    - "{{ hostname }}"
certbot_create_standalone_stop_services: []

nodejs_install_npm_user: awx_user
nodejs_npm_global_packages:
  - name: jslint
  - name: node-sass

nginx_remove_default_vhost: false