---
ansible_become: true
deploy_user: "latis_deploy"
acl_permission_users:
  - "{{ deploy_user}}"
  - "nginx"
  - "puma"


umn_user_management_directory_users:
  - name: "mcfa0086"
    revoke: no
    sudo: yes
    authorized_keys: 
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAyEflucZ6zQruAmA5I2CBTE8H6jkMsmg2giLcJ6Hb5zQvBYbqGaawXiLaPfPm8lotlTLf0XR8Q7J39qFYP3diwzYSj9IlG1NSE1nDOvbitMQFn9s08Ei9zi4TJb2rR/tmLYZLlyPsJgoJpEis2nl+IVjJ+uyu99B/94IEsudB7+YIcu11BWlpb5kuVXNkF4XLojoKHsBn9Aeb5DCvOFtzXAgWCAvsbe0b5kOnvu84EBB1wxMmNx6LPe+kd/NrwVEorgQSSX1g/raYVANALCqgVmS3kKF6iVuCBpdfPFwo8djEJPzj7V3QI0Rc2/l6AZ7xCtCU4JCsZGByDiCJ5JRQfQ== mcfa0086@umn.edu'
umn_user_management_deploy_users:
  - name: "latis_deploy"
    uid: 30000
    comment: "LATIS Deploy User"
    primary_group: "latis_deploy"
    shell: /bin/bash
    create_home: yes
    groups: []
    authorized_keys_from_directory_users: yes
    sudoers_commands: []
umn_user_management_service_users:
  - name: puma
    uid: 30001
    primary_group: puma
    shell: /bin/false
    create_home: no
    groups: []

db_hostname: ""
db_database: ""
db_username: ""
db_password: ""
secret_key: ""

nginx_upstreams:
  - name: app
    servers:
      - "unix:///var/run/puma/rails_app/rails_app.sock fail_timeout=0"

nginx_vhosts:
  - listen: "80"
    server_name: "{{ hostname }}"
    return: "301 https://{{hostname}}$request_uri"
    filename: "{{hostname}}.80.conf"
  - listen: "443 ssl http2"
    server_name: "{{ hostname }}"
    root: "/var/www/html/current/public/"
    state: "present"
    # realpath param in nginx config is necessary so that it reloads files when symlink is updated
    extra_parameters: |
      location / {
        proxy_pass http://app;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
      location ~ ^/(500|404|422).html {
        root /var/www/html/current/public;
      }
      error_page 500 502 503 504 /500.html;
      error_page 404 /404.html;
      error_page 422 /422.html;
      ssl_certificate     /etc/letsencrypt/live/{{hostname}}/cert.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{hostname}}/privkey.pem;
      ssl_protocols       TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;

ruby_install_from_source: true
ruby_version: 3.3.0
ruby_download_url: https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.0.tar.gz
ruby_install_bundler: true
ruby_build_packages:
  - '@development tools'
  - zlib-devel
  - libffi-devel

certbot_auto_renew: true
certbot_create_if_missing: true
certbot_create_method: standalone
certbot_admin_email: latistecharch@umn.edu
certbot_auto_renew_user: root

certbot_certs:
  - domains:
    - "{{ hostname }}"
certbot_create_standalone_stop_services: []

nodejs_install_npm_user: awx_user
nodejs_npm_global_packages:
  - name: jslint
  - name: node-sass

nginx_remove_default_vhost: false

puma_app_name: "rails_app"
rails_env: test
puma_app_env: '{{ rails_env }}'
puma_apps_dir: /var/www/html
# puma_threads_min
# puma_threads_max
# rails_env: development
puma_configs_dir: /etc/puma
puma_logs_dir: /var/log/puma
puma_pids_dir: /var/run/puma
puma_sockets_dir: /var/run/puma

puma_user: puma
puma_group: puma