---
- hosts: happyfuntime
  pre_tasks:
    - yum:
        pkg: "git"
        state: "present"
      become: yes
    - name: "Open https and http ports in firewalld"
      firewalld:
        service: "{{ item[0] }}"
        permanent: yes
        state: enabled
        immediate: yes
        zone: "{{ item[1] }}"
      loop: "{{ ['http', 'https'] | product(['public', 'Campus', 'Bastions']) | list}}"
    - name: "Grant latis_deploy user permissions to write to /var/www/html/"
      file:
        path: "/var/www/html/"
        state: directory
        owner: "latis_deploy"
        group: "latis_deploy"
        mode: "0755"
      become: yes
    
  roles:
    - user_management
    # - geerlingguy.apache
    - geerlingguy.repo-remi
    - geerlingguy.php
    # - geerlingguy.ruby
    # - sectigo
    - geerlingguy.certbot
    - geerlingguy.nginx
    - geerlingguy.nodejs
    - geerlingguy.redis