---
- hosts: happyfuntime
  pre_tasks:
    - yum:
        pkg: "git"
        state: "present"
      become: yes
    - name: "Open https and http ports in firewalld"
      firewalld:
        service: "{{ item[0] }}"
        permanent: yes
        state: enabled
        immediate: yes
        zone: "{{ item[1] }}"
      loop: "{{ ['http', 'https'] | product(['public', 'Campus', 'Bastions']) | list}}"
    - name: "Grant latis_deploy user permissions to write to /var/www/html/"
      file:
        path: "/var/www/html/"
        state: directory
        owner: "nginx"
        group: "nginx"
        mode: "0755"
      become: yes
    - name: "Grant latis_deploy user permissisons to write to var/www/html using an actl"
      acl:
        path: "/var/www/html/"
        entity: "latis_deploy"
        etype: "user"
        permissions: "rwx"
        state: "present"
      become: yes
    - name: "Create a /var/www/html/storage and set it to 777"
      file:
        path: "/var/www/html/storage"
        state: directory
        owner: "nginx"
        group: "nginx"
        mode: "0777"
      become: yes
    - name: "Set SELinux context for /var/www/html/"
      sefcontext:
        target: "/var/www/html(/.*)?"
        setype: "httpd_sys_content_t"
        state: "present"
      become: yes
    - name: "configure SElinux so that nginx can write to /var/www/html/<release>/storage"
      sefcontext:
        target: "/var/www/html(/.*)?/storage(/.*)?"
        setype: "httpd_sys_rw_content_t"
        state: "present"
      become: yes
    - name: "use acl to grant nginx access to /var/opt/remi/php83/run/php-fpm/www.sock"
      acl:
        path: "/var/opt/remi/php83/run/php-fpm/www.sock"
        entity: "nginx"
        etype: "user"
        permissions: "rw"
        state: "present"
      become: yes
  roles:
    - user_management
    # - geerlingguy.apache
    - geerlingguy.repo-remi
    - geerlingguy.php
    # - geerlingguy.ruby
    # - sectigo
    - geerlingguy.certbot
    - geerlingguy.nginx
    - geerlingguy.nodejs
    - geerlingguy.redis