---
- hosts: happyfuntime
  pre_tasks:
    - yum:
        pkg: "git"
        state: "present"
      become: yes
  tasks:
    - name: "Open https and http ports in firewalld"
      firewalld:
        service: "{{ item[0] }}"
        permanent: yes
        state: enabled
        immediate: yes
        zone: "{{ item[1] }}"
      loop: "{{ ['http', 'https'] | product(['public', 'Campus', 'Bastions']) | list}}"
  roles:
    # - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.ruby
    # - sectigo
    - geerlingguy.nginx
    - geerlingguy.certbot
    - geerlingguy.nodejs