---
- hosts: happyfuntime
  pre_tasks:
    - yum:
        pkg: "git"
        state: "present"
      become: yes
    - name: "enable legacy cert support, because nodejs package is current broken"
      command: "update-crypto-policies --set LEGACY"
      become: yes
  post_tasks:
    - name: "Create a /var/www/html/shared/storage and set it to 777"
      file:
        path: "/var/www/html/shared/storage"
        state: directory
        owner: "latis_deploy"
        group: "nginx"
        mode: "0777"
      become: yes
    - name: "configure SElinux so that nginx can write to /var/www/html/<release>/storage"
      sefcontext:
        target: "/var/www/html/shared/storage/(/.*)?"
        setype: "httpd_sys_rw_content_t"
        state: "present"
      become: yes
    - name: "configure SElinux so that nginx can write to /var/www/html/<release>/storage"
      sefcontext:
        target: "/var/www/html/releases/[^/]*/storage/(/.*)?"
        setype: "httpd_sys_rw_content_t"
        state: "present"
      become: yes
    - name: copy in laravel env file
      template:
        src: "env.j2"
        dest: "/var/www/html/shared/.env"
        owner: "latis_deploy"
        group: "latis_deploy"
        mode: "0644"
  roles:
    - user_management
    # - geerlingguy.apache
    - geerlingguy.repo-remi
    # - geerlingguy.ruby
    # - sectigo
    - geerlingguy.certbot
    - geerlingguy.nginx
    - webapp
    - geerlingguy.php
    - geerlingguy.nodejs
    - geerlingguy.redis