- name: geerlingguy.apache
- name: geerlingguy.php
- name: geerlingguy.repo-remi
- name: geerlingguy.certbot
- name: geerlingguy.nginx
- name: geerlingguy.ruby
- name: geerlingguy.nodejs
- name: geerlingguy.redis
- name: sectigo
  src: git+https://github.com/umn-ansible/umn_sectigo_role.git
- name: user_management
  src: git+https://github.com/umn-ansible/umn_user_management_role.git